version: "3"
services:
  front_end:
    build:
      context: .
      dockerfile: Dockerfile
    image: front_end
    container_name: front_end
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    networks:
      my-bridge-network:

networks:
  my-bridge-network:
