version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobile_online_shop
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      my-network:

  back_end:
    container_name: back_end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      my-network:

  front_end:
    container_name: front_end
    build:
      context: ../front_end
      dockerfile: ../front_end/Dockerfile
    ports:
      - "3000:3000"
    networks:
      my-network:

networks:
  my-network:
    external: true
volumes:
  mysqldb:
    external: true